Add graphics library
nolasconapoleao/slingsim pull request #3
Opened 2021-04-10 17:57 UTC by nolasconapoleao

2021-04-13 22:19 UTC, Dimiz requested changes

2021-04-13 22:19 UTC, ghost commented on libs/src/CMakeLists.txt
>  add_subdirectory(libsample)
order

2021-04-13 22:19 UTC, ghost commented on libs/src/graphics/draw.cpp
> +void draw(const Point2d &point, const Colour &colour) {
I would use render terminology instead of draw.
And you could create an object for each object type you want to render.

2021-04-13 23:00 UTC, nolasconapoleao commented on libs/src/CMakeLists.txt
>  add_subdirectory(libsample)
it is in alphabetical order, do you mean reorder it?

2021-04-13 23:00 UTC, nolasconapoleao commented on libs/src/graphics/draw.cpp
> +void draw(const Point2d &point, const Colour &colour) {
yep fair point render sounds better.
What is the object part, do you mean define an enum for this?

2021-04-14 18:23 UTC, Dimiz commented on libs/src/CMakeLists.txt
>  add_subdirectory(libsample)
yes I meant to reorder to alphabetical order

2021-04-14 18:33 UTC, Dimiz commented on libs/src/graphics/draw.cpp
> +void draw(const Point2d &point, const Colour &colour) {
I would say to make a separation between calls. If you are rendering a Line, create an object called Line with a function render, and so on.

2021-04-17 17:50 UTC, merged